bethlakshmi/GBE2

.gitignore
expo/gbe/forms.py
expo/gbe/functions.py
expo/gbe/templates/gbe/incl_contact_form.tmpl
expo/gbe/templates/gbe/incl_lp_left.tmpl
expo/gbe/urls.py
expo/gbe/views.py

This pull request gives us the minimal case of a contact form. USER_CONTACT_RECIPIENT_ADDRESSES controls the recipient list. 
Some caveats:
*I haven't done anything about styling of the contact form, this is just about the functionality.
* I'm concerned about the testability of this code, but addressing that means going back to the vagrant idea - setting up a local testing machine provisioned for testing stuff like sending email. That's a big job
* One improvement to this will be to log the use of this feature, since a form of this sort is obviously a spam magnet. Need to approve and merge the logging branch for this to happen. 
* Another improvement will be to throttle the use of this rather severely. For example, rejecting out of hand any attempt to send more than once in any …

Basics of contact form

---

expo/expo/settings.py

Closes #552.
This time as the right issue number.

GBE 552:  Remove "en" to fix vanishing & reappearing Edit bug in Django CMS

---

expo/scheduler/models.py
expo/scheduler/templates/scheduler/event_detail.tmpl
expo/tests/factories/scheduler_factories.py
expo/tests/functions/gbe_functions.py

Closes #630.  
I would have rather done a distinct(‘role’, ‘_item’), but Django 1.6 with MySql doesn’t support this (it requires Postgres).
I tried a number of value() permutations but that flattens the query set into a dict, which breaks the expectations of the functional footprint.
This removes the duplicates from this specific thread.  The function is used other places, so one bonus is, it doesn’t change any other thread.

GBE-630: Remove duplicate cases of worker in event details

---

expo/gbe/templates/gbe/incl_schedule.tmpl
expo/gbe/templates/gbe/landing_page.tmpl
expo/gbe/views.py
expo/tests/gbe/test_landing_page.py

Closes #581
———————
Now testing is complete - it tests:
- that a current scheduled class is shown in regular mode
- that a past class is shown in historic mode
- that a current scheduled volunteer opportunity is shown in regular
mode
- that a past scheduled volunteer opportunity is shown in historic mode
And also vice, versa that things that are in regular mode are NOT in
historic mode and things in historic mode are NOT in regular mode.
Of note- getting the timestamps right is super nitpicky and I couldn’t
emulate it perfectly, but this should demonstrate that the timestamp is
not completely wrong.
Also - I chose not to test act assignment - it is one more logical
thread, but it was just one too many, and is not part of the code
changes that I affected in the update.
————————— …

GBE 581:  Landing page schedule fixed for multiple conferences.

---

expo/gbe/forms.py
expo/gbe/static/styles/base.css
expo/scheduler/templates/scheduler/manage_opps.tmpl
expo/scheduler/views.py

closes #608
(this time, for real)
- CSS reformatting to reduce the size of # of volunteers needed and duration
- less wordy buttons to make action column smaller
- changed header from “Volunteers Needed” to “#” to save space
- streamlined error messaging to fit a smaller row-based context.

GBE 608: Improving volunteer management

---

expo/gbe/models.py
expo/tests/gbe/test_review_volunteer_list.py

Closes #654
- fixes a problem on 
http://localhost:8282/volunteer/reviewlist
Where a volunteer with bookings from 2015 has their booking show up.  Because the booking also don’t show date, it looks like they are current to this year, making the visual really confusing.
The fix is to screen out all commitments that are NOT a part of this conference, and also to show the date, the way we do with volunteer windows, so it is clearer what the commitment is.

GBE-654: Comments on review volunteer list page not filtered per conference

---

expo/gbe/static/styles/gbe_bootstrap.min.css
expo/templates/base.tmpl
expo/templates/menu.tmpl

- submenus appear
- positioning is not horrific
- fix an existing bug in menu.tmpl - no spaces in classes mean one big
class.
To Test:
- pull the latest data from GBE Live
- make sure you have a clean browser refresh for CSS and JS
- go to Shows & Events —> All Shows
NOW - you will see that there are 4 shows, each with a working page.
The sub menu is positioned to the right of the parent menu item and the rest of the menus in the system appear in a reasonable position relative to their parents.
Prior to this fix, this did not work - submenus didn’t appear.
Closes #656

GBE-656: Submenus not working in Django-CMS 

---

expo/tests/gbe/test_reports.py

@bethlakshmi if you'd rather add this to GBE-732, that's fine with me, just leave a comment and close this PR. Up to you.

GBE-736: Remove "time bomb" from test_reports.py

---

config/requirements.txt

Installing ipython on the vagrant box causes manage.py to select it by default
Locked us to version 3.0 since current versions produce much deprecation warnings. Can unlock this when we get the upgrade going.

GBE-744: Install ipython shell, django will select it by default

---

expo/tests/scheduler/test_event_list.py

Closes #774 
There’s one line in “get_events_display_info” that I can’t get coverage for - line 111.  I’m wrestling with pulling it - it’s a fair line, but all the models we have would require serious messing around.  
EventFactory doesn’t work on it’s own (I get an error when I try to just create a raw EventFactory event - or that would be a decent vehicle for this case.

GBE-774 scheduler.event_list coverage

---

expo/gbe/views/review_act_view.py
expo/gbe/views/review_class_view.py
expo/gbe/views/review_costume_view.py
expo/gbe/views/review_vendor_view.py
expo/gbe/views/review_volunteer_view.py
expo/tests/gbe/test_review_act.py
expo/tests/gbe/test_review_class.py
expo/tests/gbe/test_review_costume.py
expo/tests/gbe/test_review_vendor.py
expo/tests/gbe/test_review_volunteer.py

looked at the bug and saw we had inconsistent implementation across functions in the various mappings from review_(bid type) to the view_(bid type) when the conference has passed.
I made them all reverse url lookups, and then wrote tests for that in every test area.  Also noticed some test collections that didn’t include a login and permission check and so added those, too. 
Lastly, any test case I touched, I refactored to remove nose.
Fixes #794

GBE 794:  Reverse URL lookup to get to view_* (any bid)

---

expo/gbe/views/edit_act_techinfo_view.py
expo/gbe_forms_text.py
expo/tests/gbe/test_edit_act_techinfo.py

Makes the failing test pass.
Refactored code to use the same act info setup code regardless of post
or get, and used the working get process instead of the post process.
A way to see the problem in integration is to follow the steps of #817 before and after the fix.
closes #817

GBE 817 - fix for errors in Act Tech Info submit cause messed up information display on top of page.

---

config/requirements.txt

support our configuration. 
To test, pull a new clone of the repo. Stand up the vagrant box and attempt to run tests or get into the django shell - should fail. Then check out this branch and do a 
`vagrant reload --provision
`
or 
`vagrant destroy
vagrant up
`
Then ssh in and run tests. Should succeed.

GBE-831: Lock down cmsplugin-filer and django-nose to versions that

---

config/requirements.txt
expo/expo/settings.py

This needs one additional change - in your local_settings.py add:
INTERNAL_IPS = (
‘your_ip_here’)
The IP address has to be the address of the browser you’re connecting from.  I found this using a variant of this trick:
http://stackoverflow.com/a/14697123/49962
to get my settings to work correctly.
The verification is:
- the debug toolbar shows up when you navigate to our site in your browser (if the local settings are debug set to True)
- unit tests run
I’ll say honestly - the toolbar slows execution to a crawl, so we may need to debug to do other testing, but the SQL panel is pointing out some inefficiencies that I’m eager to fix (500+ queries on the /gbe landing page, 2000+ queries on one of the bid review pages) - so it’s definitely useful.

GBE 828:  Django-debug-toolbar arrives

---

expo/expo/settings.py

There’s a missing line that matters when you run in Apache rather than ./manage.py run server.

GBE-844: This is why we can't run on webfactional

---

expo/gbe/views/act_display_functions.py

This shouldn't happen, but if someone does have two acts with conflicting names the get() call fails hard. This is not a great solution - it redirects them to one of the two conflicting acts - but at least it doesn't die in flames.

GBE-866: Prevent server error if user has two existing acts with name conflicts

---

.gitignore
config/requirements.txt
expo/expo/settings.py
expo/gbe/cms_plugins.py
expo/gbe/templates/gbe/ad-rotator.tmpl
expo/tests/gbe/test_gbe_cms_plugins.py

- needs a reprovision of vagrant.
- after reprovision and re-setup, do a migrate
you can see the work manually by:
- go to localhost:####
- use a user that can edit django-cms (scratch and betty can)
- in the top white bar, click edit
- click structure
- insert a plugin in any box (it’s inserted through the menu in the upper right hand corner of the box.
- plugin is in the GBE area and called Ad Rotator.
——
Then go to /admin
- see that there is now “Ad_Rotator”
- and in it “Banner ads”
- you have to add banner ad items with start/end dates before and after now.
——
When you’ve set up both a page with the banner ad, and the images themselves, the ad picture will appear on refresh

GBE-255: add an ad-rotator

---

expo/gbe/report_views.py
expo/gbe/views/act_changestate_view.py
expo/gbe/views/admin_profile_view.py
expo/gbe/views/assign_volunteer_view.py
expo/gbe/views/bid_changestate_view.py
expo/gbe/views/class_changestate_view.py
expo/gbe/views/costume_changestate_view.py
expo/gbe/views/edit_act_techinfo_view.py
expo/gbe/views/edit_act_view.py
expo/gbe/views/edit_class_view.py
expo/gbe/views/edit_costume_view.py
expo/gbe/views/edit_persona_view.py
expo/gbe/views/edit_troupe_view.py
expo/gbe/views/edit_vendor_view.py
expo/gbe/views/edit_volunteer_view.py
expo/gbe/views/landing_page_view.py
expo/gbe/views/profile_view.py
expo/gbe/views/review_bid_list_view.py
expo/gbe/views/review_bid_view.py
expo/gbe/views/review_profiles_view.py
expo/gbe/views/update_profile_view.py
expo/gbe/views/vendor_changestate_view.py
expo/gbe/views/volunteer_changestate_view.py
expo/scheduler/views.py

I’ve disabled caching from:
- all edit bid pages
- all review bid list display pages
- all voting and change state action pages (so that you can see what you voted or changed most recently when reloading)
- profile management - both for admin and regular users
- the landing page for a logged in user
- volunteer assignment
- scheduler views - the privileged areas - event edit, the event editing list displays, act scheduling, contact email lists 
- reports that are focused on print runs, vs. regular reviews
The following will still have a 10 minute cache:
- pages that are primarily for static public view (event details, event view-only lists, fashion fair, show/act displays)
- pages with no user-made data (submit for the first time pages - like create bids, create profiles, etc)
- pages …

GBE-908:  Selected caching disabled

---

expo/gbe/functions.py
expo/gbe/models/remains.py
expo/scheduler/templates/scheduler/allocate_volunteers.tmpl
expo/scheduler/templates/scheduler/event_schedule.tmpl
expo/scheduler/views.py
expo/tests/contexts/volunteer_context.py
expo/tests/functions/scheduler_functions.py
expo/tests/scheduler/test_show_volunteer_info.py

Example for viewing (based on a database of data from live this year)
http://localhost:8282/scheduler/edit/GenericEvent/2306
If you’re working on data made by hand, to see the change you need to be working on a scheduled volunteer opportunity (meaning both a Generic Event and a scheduler.Event) with some # for max volunteer.
What you will see is a table at the bottom of the page labeled ‘Volunteers for (name of conference)’ that appears below the ‘Volunteer Allocation’ table.  If you don’t see the ‘Volunteer Allocation’ table - you are on the wrong page.
The new functionality should do everything in #655 plus, you can pick the role when assigning the volunteer, and you can go to the conflicting event (when there are conflicts) and edit the allocation there to remove conflicts.

GBE-655:  Better volunteer info on assignment to opportunity.

---

expo/gbe/views/volunteer_display_functions.py
expo/tests/gbe/test_review_volunteer.py

Did as we spoke about last scrum:
- updated volunteer display to show only the chosen available time slots, unavailable time slots, state, and how heard selections.
As a side benefit of refactoring, the same code covers review volunteers (http://localhost:8282/volunteer/review/640) and view volunteer (http://localhost:8282/volunteer/view/640) so now both are clean.
Made a unit test set (4 tests) for the four things I changed, both positive and negative cases.

GBE 699: clean up volunteer review

---

expo/gbe/report_views.py
expo/gbe/templates/gbe/report/act_tech_review.tmpl
expo/tests/gbe/test_reports.py

Test;
- if you have BOTH ‘Tech Crew’ and ‘Schedule Mavens’ - then:
- on 
http://localhost:8282/reports/acttechinfo/view_summary/545
you will see “Schedule Acts for this Show” 
This will take you to:
http://localhost:8282/scheduler/acts/532
With the show I’ve referenced, there are no currently scheduled acts in our test data… but if you pick a show from an older conference, you’ll also see a table of information on each page (the table works differently between the pages).

GBE-678: Add a link to schedule Acts for the given show on the act tect info report.

---

expo/gbe/models/remains.py

This is a one line change - test by;
- on master: go to http://localhost:8282/costume/create
- see that Costume Creator has a * but is not bold.
- on this branch - go to the same place.
- It is now bold.
The display is controlled by a switch in models - I just made sure it had the right value.  Anything required for the draft should be in bid_draft_fields.

GBE-763: Add creator to required draft fields.

---

expo/gbe/forms/remains.py
expo/gbe/templates/gbe/bid.tmpl
expo/gbe_forms_text.py
expo/tests/gbe/test_create_volunteer.py

- put a check in Volunteer Bid form to prevent this.
- it will throw an error for both the available field (with details) and the unavailable field
- found that the top of the form did not give an error, so fixed the code that used to throw this alert
- found some dead code and removed it in this area.
———————
to test:
- seed your database with current data or make a conference that has volunteer windows in it.
- try to submit a volunteer bid (/volunteer/bid) with the same time slot marked for available and unavailable.
- see it give you errors.
The same thing will happen for volunteer editing (volunteer coordinators can edit a volunteer bid on the review volunteers page - there is an option for ‘edit’)

GBE 933: Throw error when user tries to submit same time slot as unavailable and available.

---

expo/gbe/forms/remains.py
expo/scheduler/forms.py
expo/scheduler/functions.py
expo/scheduler/views/remains.py
expo/tests/scheduler/test_detail_view.py

All the hard coded dates are dead code.  I removed them and refactored the one set that was actively in use to the file that was actually using it.
Reran all tests
gripped for any cases of the code - couldn’t find any

GBE 546: remove hard coded dates

---

expo/gbe/functions.py
expo/scheduler/functions.py
expo/tests/scheduler/test_calendar_view.py

I found a pretty clean, pretty small point of separation in this one function.
it not longer knows anything about gbe.models - but this increases the need to import gbe.model elements in gbe.functions — > many of which were originally failing in the original problem.

GBE 950: separate conference list from schedule build

---

expo/gbe/views/act_display_functions.py
expo/gbe/views/review_act_view.py
expo/gbe/views/view_act_view.py
expo/tests/gbe/test_review_act.py

addresses #856 using the same trick used on other tickets - overload the form with only the choice that was selected.
Since the bug affects both ‘view’ and ‘review’ - I refactored them both to use a shared function.

GBE-856: show only video selection

---

expo/gbe/templates/gbe/bio_list.tmpl
expo/gbe/views/bios_teachers_view.py
expo/scheduler/functions.py
expo/tests/gbe/test_bios_teachers.py

To manually test - 
- 709 - if you’re using recent data, compare: 
http://www.burlesque-expo.com/bios/teachers?conference=GBE2016
and 
localhost (same URL)
Around ‘Roman Sirotin’ the view is messed up on the site, and OK on the  fixed branch.  Also - if you want to check the django-cms - you can now add a placeholder image via django-cms, so that I don’t have to care what image Scratch wants.
————
945 - also notice that if you use the current conference (http://localhost:8282/bios/teachers), the accepted classes show up, even if they aren’t scheduled yet.
Unscheduled classes don’t have details that show up in the scheduler views, so the teacher’s classes are listed by title w no link when they are unscheduled, and with a  link after they are scheduled for a time and date.

GBE 945&709: show accepted class, and add a way to put an image for teachers with no photo

---

expo/gbe/templates/gbe/register.tmpl
expo/gbe/views/create_volunteer_view.py
expo/tests/gbe/test_create_volunteer.py

#961 
Fix the flow to go to registering an account on the premise that most volunteers are new to the expo.  As it turned out “login_required” as an annotation will ALWAYS route you to the login page, not to the account page.  So I had to remove it.  Our logic inside the function protects us anyway.
Also fix wording.
Since I tweaked the logic, I also updated the test to be more specific (it would have passed either way).

GBE 961: make volunteer registration easier

---

expo/gbe/ticketing_idd_interface.py
expo/gbe/views/bid_act_view.py
expo/gbe/views/create_vendor_view.py
expo/gbe/views/edit_act_view.py
expo/gbe/views/edit_vendor_view.py
expo/tests/functions/gbe_functions.py
expo/tests/gbe/test_bid_act.py
expo/tests/gbe/test_create_vendor.py
expo/tests/gbe/test_edit_act.py
expo/tests/gbe/test_edit_vendor.py

Added a filter to check that only acts and fees within a conference are compared.  
A way to test - using the betty account, try to submit a vendor and act on this year’s conference - it will fail because although I have spare fees, they are on old conferences.
This can also be done in reverse - find a current conference bidder (act or vendor), make sure act/vendor is not submitted.  Remove older transactions for fees from old conferences, and check that it’s still OK to re-submit the act bid.

GBE 955: check fees per conference

---

expo/gbe/models/act.py
expo/tests/contexts/show_context.py
expo/tests/gbe/test_review_act_list.py

#957 is a bug that came from refactoring the models.py into /models/*.py
In so doing, we didn’t import ResourceAllocatino, and the way the code was written, it failed silently and had no unit test backup.
Refactored and added code to:
- use scheduler in a way that means less cross-model contact.
- add unit tests to keep failure from remaining silent.

GBE 957: Show shows on act/reviewlist

---

expo/gbe/models/act.py
expo/gbe/models/profile.py
expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/update_profile.tmpl
expo/gbe/views/create_volunteer_view.py
expo/gbe/views/register_view.py
expo/gbe/views/update_profile_view.py
expo/gbetext.py
expo/tests/gbe/test_create_volunteer.py
expo/tests/gbe/test_register.py
expo/tests/gbe/test_update_profile.py

There are details on the bottom of #699 of all the navigational paths.  I made sure that no matter what you do, the system will detect what you’re missing and get you to the right screen to fix it.
Put in the error message we wanted when a volunteer is found to be missing profile info.
Put in check that a profile is not “complete” if it does not have a display name and an email.

GBE 699: prevent volunteers from submitting with no phone or badgename

---

expo/scheduler/forms.py
expo/tests/scheduler/test_schedule_acts.py

The manual test is pretty easy:
- use a recent dump of GBE
- go to ‘http://localhost:8282/scheduler/acts'
- select a show
- see that only 4 shows and “—“ show up.  And they load quite fast.
That’s it.  If you look at master, you’ll see the list gruesomely long, loads slow and expands off the real estate.

GBE 912: only show the shows for this conference

---

expo/gbe/functions.py
expo/gbe/templates/gbe/email/default_bid_status_change.tmpl
expo/gbe/templates/gbe/email/default_bid_status_change_html.tmpl
expo/gbe/views/act_changestate_view.py
expo/gbe/views/bid_changestate_view.py
expo/tests/gbe/test_act_changestate.py

Change = when an act bid is accepted (Review -> Acts, select act, click Review, change the form on the right to accept and submit) - then the “act accepted” email now tells them what show they were cast into and creates/uses a specific template for that show (so there is 1 template for rhinestone review, 1 template for main event, etc).
Waitlist, reject, withdrawn, etc - do not do a per show view.
Fun fact:  there are 525 lines out of 6815 of code that are NOT tested.  A month ago, there were ~583 lines.  If we hit 504 lines of untested code, we will be at 93% coverage.

GBE 949: Accept Act is now show-sensitive

---

.gitignore
config/requirements.txt
expo/expo/settings.py
expo/expo/urls.py
expo/gbe/models/class_model.py
expo/gbe/templates/gbe/assign_volunteer.tmpl
expo/gbe/views/assign_volunteer_view.py
expo/scheduler/models.py

On my test set, this brought me down to a little worse than 50% faster and with 1/2 the SQL queries.
To be even faster, I put caching back on the page.
Added django debug tool bar back, and had to fix some dependancies - if you want to test this with django debug toolbar, you’ll probably need to retrovision your vagrant.

GBE 979: Speed up assign volunteers

---

expo/gbe/static/styles/base.css
expo/scheduler/functions.py
expo/scheduler/templates/scheduler/sched_display.tmpl
expo/scheduler/views/remains.py

This was all visual fixing, so no unit tests were added.  Same level of coverage as master.
Changes:
- changed the size of a block (i.e., a row in the table) to be 30 minutes
- this made the far left column ugly, so I tuned it to only show time, and have a fixed width
- to compensate for removing the date - I put the date at the top as a header.  Given that the function does both per-day, and a date range, I offered both options for date display.
- pepdiff = no problems
- unit tests - all run
- run coverage = 528 missing lines

GBE 983: display by half hour

---

expo/gbe/static/styles/gbe_bootstrap.min.css
expo/gbe/static/styles/menustyle.css
expo/templates/base.tmpl
expo/templates/menu.tmpl

You can now click on a submenu, then click on a different submenu and
the old one will close, and the new one will open.
Sadly, this does NOT fix the mobile phone  menu problem.  What I did to customize the CSS way back when plays out VERY badly on smart devices.  
Because this offers a meaningful improvement, I’m pulling.  I intend to continue to fight the mobile  battle later.

GBE-978: Fixes the two menu open problem

---

expo/gbe/models/show.py
expo/gbe/reporting/report_views.py
expo/tests/gbe/test_reports.py

This is the clean fix for what I had to hot fix on the live site.  We definitely need this to be in master before the next push to live.
This includes:
- the two bug fixes needed to make download all tracks work on Special -> Report -> Summary of Act Tech Info -> pick a show -> choose download all audio (bottom of page)
- a unit test to catch the error - had we had this test, we wouldn’t have created these bugs in refactoring code.
It also happens to raise coverage to 93%  - :D
Should be pretty straight forward.

GBE 997: URGENT - fix 500 error in download audio

---

expo/expo/settings.py
expo/gbe/templates/gbe/profile_review.tmpl
expo/gbe/urls.py
expo/gbe/views/__init__.py
expo/gbe/views/delete_profile_view.py
expo/gbe/views/review_profiles_view.py
expo/gbetext.py
expo/tests/gbe/test_delete_profile.py
expo/tests/gbe/test_review_profiles_view.py

On Special -> Manage -> Users
- there is a Delete option if you are a registrar
- it will either deactivate if there are related conference artifacts, or delete if this is really a user who did nothing with us.
- It gives an alert
There’s a lot of tests because there’s a giant if statement.

GBE 971: delete users on user management page

---

.gitignore
config/requirements.txt
expo/expo/settings.py
expo/gbe/forms/remains.py
expo/gbe/templates/gbe/register.tmpl
expo/templates/base.tmpl
expo/tests/gbe/test_register.py

Adding the “I am not a robot” checkbox to the site.  Used this django plugin:
https://github.com/kbytesys/django-recaptcha2
Instructions to test:
- rebuild vagrant (aka, install the plugin)
- set this in your local host:
RECAPTCHA_PRIVATE_KEY = '6Le0dx0UAAAAACNZynxCx5mUovu3M1Au3XFeeFKN'
RECAPTCHA_PUBLIC_KEY = '6Le0dx0UAAAAAFGd_HJzX22FdzhwI-GCh8nCoXoU'
Your machine should read as 127.0.0.1 for this to work.  
These are our test keys and will ONLY work on your local…  the other keys are installed only on the servers.
Since this is a potentially annoying package install, I won’t pull it until I test this branch on the test site.  If there’s no comments, pulling to master and pushing to live will happen quickly after that.

GBE-956: Add Google2 Recaptcha

---

expo/expo/settings.py

this is a several line change to settings.py.
Reran tests
pepdiff no changes
tested manually that server is OK locally and “en” is removed.

GBE-2015: remove 'en' from language settings.

---

expo/gbe/functions.py
expo/tests/functions/gbe_functions.py
expo/tests/gbe/test_act_changestate.py

When the system is set to debug, the email is sent to the ADMINS (the django setting), instead of the regular user.  This is a preventative on the wdbfactional test server - I need to test that the email system actually works end to end, but when the email is sent, I don’t want to freak out users.

GBE 1017: mail sent to ADMINS when on Debug

---

expo/gbe/views/edit_act_techinfo_view.py
expo/tests/gbe/test_edit_act_techinfo.py

This checks the validity of the act tech forms *as a whole* then saves them all if the validity passes.  This keeps the user from saving partial data, only to get a failure, and it keeps us from silent failures by checking overall validity before declaring success.
pepdiff done
test added
runcoverage - same value of uncovered lines.

GBE-1013:  check validity of act tech

---

expo/gbe/views/create_event_view.py
expo/tests/gbe/test_create_event.py

When I dug in, this was really a bug from the django 1.8 upgrade - when we separated b_* and e_*, we should have made sure that class create through scheduler included both parts, and not just e_* data.
Fixed that with a fast switch, and added a test

GBE-1021: fix bug in create event for classes

---

expo/transaction_cron_job.py

recommended for django 1.8
wasn’t needed for 1.6
To test - you are best setting up a cron job.  Alternately, run python fro the command line. 
I recommend syncing against a copy of our DB, and deleting a transaction in ticketing, so that you know your ticket sync did something.

Fix ticket import for django 1.8

---

expo/gbe/ticketing_idd_interface.py
expo/tests/gbe/test_create_act.py
expo/tests/gbe/test_create_vendor.py
expo/tests/ticketing/test_transactions.py

only 1 person could ever submit, because the logic was “get all the submitted acts and compare them to what this person paid for.”
So after 1 person submits, the next person (who only bought 1 fee), can’t submit.  
The filter to check only for THIS user’s act submissions was washed away in a ticket update I made in Feb.
Fixed the bug in both acts and vendors, and then made tests to cover the back

GBE-1014: fix bug on ticketing

---

expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/update_profile.tmpl
expo/templates/form_table.tmpl

#1034
I actually ended up affecting all the forms… for the better:
- put bootstrap containers around the two columns in Update Profile - now when the screen is small, the right side column goes below the left.
- put bootstrap columns in place of the table format in all forms using form_table.tmpl.  Layout on regular screen is largely the same, but on a small screen, the label is shown ABOVE the field.  That looks much better on a cell phone.
There’s more that can be done but this is a big improvement.

GBE 1034:  Bootstrapify the Update Profile Form

---

expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/landing_page.tmpl
expo/templates/base.tmpl

Used bootstrap to update the 3 column layout for this form.  It shouldn’t look too different on a desktop/laptop, but on a tablet/phone below ~760px, it will become 3 tabs instead of 3 columns, letting each column consume 100% of the space when the tab is selected.
I jiggered a bit with the look of the tabs in the hopes of it being clear that this area is lower than the main menu structure.

GBE 1039: Bootstrapify user landing page

---

expo/gbe/admin.py
expo/gbe/migrations/0007_actcastingoption.py
expo/gbe/migrations/0009_actcastingoption.py
expo/gbe/models/__init__.py
expo/gbe/models/act.py
expo/gbe/models/act_casting_option.py
expo/gbe/static/styles/base.css
expo/gbe/static/styles/gray_grids_css/main.css
expo/gbe/views/act_changestate_view.py
expo/gbe/views/act_display_functions.py
expo/gbe/views/review_act_view.py
expo/gbetext.py
expo/scheduler/admin.py
expo/scheduler/migrations/0002_actresource_role.py
expo/scheduler/models.py
expo/scheduler/templates/scheduler/event_detail.tmpl
expo/scheduler/views/functions.py
expo/templates/featured_people.tmpl
expo/templates/people_gallery.tmpl
expo/templates/people_modal.tmpl
expo/tests/contexts/act_techinfo_context.py
expo/tests/contexts/show_context.py
expo/tests/factories/gbe_factories.py
expo/tests/gbe/test_act_changestate.py
expo/tests/gbe/test_review_act.py
expo/tests/gbe/test_review_act_list.py
expo/tests/scheduler/test_detail_view.py

- Scratch can define what types of roles a given act fills, le host, feature act, etc. with an admin switch
- act coordinator can “cast” the act into one of these roles in the act review pages.
- the act review table shows the casting as a nice FYI.
- the featured acts of any special type get their own grid display in the event detail view.
This requires a migrate in gbe & scheduler
To use, it has to be manually seeded with feature acts.
#393

GBE 393: make feature acts

---

expo/gbe/static/styles/base.css
expo/scheduler/templates/scheduler/event_detail.tmpl

This is all templates and CSS
#1056 
There are two things to test:
- a just-accepted class with no schedule details
- a scheduled class
They are built differently, but should render the same.
May need some fussy checking when the other pull request is merged.

GBE-1056: Fix look of non-shows in event details

---

expo/templates/ticket_link.tmpl
expo/tests/gbe/test_get_tickets.py
expo/ticketing/functions.py
expo/ticketing/models.py

#1080 
fixed the view on event details in light of the new BPT title that should be the displayed title.

GBE 1080: make ticket names be event names

---

expo/gbe/models/profile.py
expo/tests/gbe/test_landing_page.py

On the landing page, the way bids were considered “reviewed” was if they had a bid eval.  I think it was actually broken for the last specialized act review way, too… but now it’s updated for flexible evals.
Wrote a test, since we didn’t have one.

GBE-1126:  Make new review process reflected on landing page

---

expo/gbe/email/forms/select_bidder_form.py
expo/gbe/email/views/mail_to_bidders_view.py
expo/gbe/templates/gbe/email/mail_to_bidders.tmpl
expo/tests/contexts/class_context.py
expo/tests/gbe/email/test_mail_to_bidders.py

Added Drafts to the bid states
Turned bid states into checkboxes so that “Drafts” are all not-submitted bids, and then the other states apply to only submitted bids and the value of the acceptance field.
That meant a lot of mucking into the filter to make the checkbox display look nice.

GBE 1140: make draft a bid state

---

expo/gbe/forms/audio_info_form.py
expo/tests/gbe/test_edit_act_techinfo.py

Fixes the problem in track duration by checking the data differently and throwing an error instead of the 500 error.
#1170

GBE-1170:  Fix Lili's bug - correctly check track duration

---

expo/gbe/templates/gbe/assign_volunteer.tmpl

Fixes #1177 
The fix was easy and well known - include the datatable CSS and JS files.
This also fixed the issue with the special menu.  I surmise that the epic fail of the JS at the end of this page, that controls the data tables, somehow took down the JS for the special menu, too.

GBE-1177: Assign volunteers missing CSS & JS for DataTables

---

expo/gbe/views/view_troupe_view.py
expo/tests/gbe/test_edit_troupe.py
expo/tests/gbe/test_view_troupe.py

the bug was that the view doesn’t consider the case when the user is NOT the troupe contact.  So the “contact info” part of the display is actually seeded with the current user’s info.
In looking at this, it was clear that this is a REALLY old and fairly incomplete - the most obvious problem was that there is NO access control on this, other than that the user is logged in.  That sucks, since there is personal contact info here, and any random user could game the system and harvest troupe contact details.  Ick. 
Fixed that, couldn’t leave it alone.
Also, the testing in this area was the most trivial tests imaginable, so I added both better checks AND more tests for my new cases and the bug fix.

GBE 1176:  Fix & improve view troupe info

---

expo/gbe/scheduling/views/show_calendar_view.py
expo/tests/gbe/scheduling/test_calendar_view.py

Don’t help URL hackers game the system… throw the same error regardless of the problem - 404, not found.

GBE-1203:  Throw HTTP 404 when format is bad

---

expo/scheduler/idd/update_occurrence.py
expo/tests/gbe/scheduling/test_edit_event_schedule.py

0 counts as false in “if max_volunteer” so it avoided ever getting updated.
Changed logic to not None and it all works.
Wrote a test as a safety check

GBE-1212: Correct logic check

---

expo/gbe/email/functions.py
expo/gbe/scheduling/views/allocate_worker_view.py
expo/gbe/scheduling/views/functions.py
expo/gbe/templates/gbe/email/volunteer_schedule_update.tmpl
expo/gbe/templates/gbe/email/volunteer_schedule_update_html.tmpl
expo/gbe/views/act_changestate_view.py
expo/gbe/views/bid_changestate_view.py
expo/gbe/views/volunteer_changestate_view.py
expo/gbetext.py
expo/tests/functions/gbe_functions.py
expo/tests/gbe/scheduling/test_allocate_workers.py
expo/tests/gbe/test_act_changestate.py
expo/tests/gbe/test_volunteer_changestate.py

The problem in #1206 triggered #1209 which then spawned #1210 for later.
I did the following:
- made a better working link to home page for the schedule update email.  REMINDER - update the instructions and the template when it’s installed.
- made error handling and a catch of any exceptions that are thrown from the email generation process.  When the user is a privileged person, the problem is shared as a error message in our typical pattern.

GBE-1209 & 1206: Fix problems in templates

---

expo/gbe/email/forms/adhoc_email_form.py
expo/gbe/email/views/mail_to_bidders_view.py
expo/gbe/email/views/mail_to_filter_view.py
expo/gbe/email/views/mail_to_person_view.py
expo/gbe/email/views/mail_to_roles_view.py
expo/gbe/email/views/mail_view.py
expo/gbe/templates/gbe/email/mail_to_group.tmpl
expo/gbe/templates/gbe/email/send_mail.tmpl
expo/templates/form_field.tmpl
expo/tests/gbe/email/test_mail_to_bidders.py
expo/tests/gbe/email/test_mail_to_person.py
expo/tests/gbe/email/test_mail_to_roles.py

for both mail to bidders and mail to roles, the user can now deselect people from the “to” list for the email.  The code still checks the validity of the full list to make sure that nothing got snuck in there.
To make this all readable, I reduced the to list to only names, not emails.

GBE 1161:  be able to remove email recipients from ad hoc mail

---

expo/gbe/forms/participant_form.py
expo/gbe/migrations/0023_clean_display_name.py
expo/gbe/views/update_profile_view.py
expo/tests/gbe/test_update_profile.py

Ended up cleaning up a bunch - 
- display name has no whitespace start/end
- display name has only 1 space between words
- display name is title case (caps on first letter)
This cleans up on submit, and also has a migration to clean up old data, once and for all.
The side effect will be that users always get a nice-looking display name.  If they have chosen some artistic way of representing their name - like all small letters or 3 spaces - too bad, we will forcibly clean them.

GBE 1223: Make sure display name is always clean
