expo/templates/readonly_form_table.tmpl

Just needed the media url in the file link.

Closes #452

---

expo/gbe/forms.py
expo/gbe/menu.py
expo/gbe/models.py
expo/gbe/static/styles/base.css
expo/gbe/static/styles/gbe_bootstrap.min.css
expo/gbe/templates/gbe/bid_review.tmpl
expo/gbe/templates/gbe/class_proposal.tmpl
expo/gbe/templates/gbe/fashionfair.tmpl
expo/gbe_forms_text.py
expo/scheduler/templates/scheduler/event_detail.tmpl
expo/scheduler/templates/scheduler/event_display_list.tmpl
expo/scheduler/templates/scheduler/event_schedule.tmpl
expo/scheduler/templates/scheduler/manage_opps.tmpl
expo/templates/form_table.tmpl
expo/templates/readonly_form_table.tmpl

Collection of fixes to correct visual breakage and make site more consistent with Django-CMS styling.
Major areas of work:
- putting MEDIA_URL in image tags wherever I could find them
- adding classes for typical font styles to templates
- styling CSS in GBE
- Made large lists (>7) of checkboxes display in 2 columns
- alphabetized long lists of checkboxes
- PEP-8 fixing in *.py files that were text-only files

GBE visual fix

---

expo/gbe/functions.py

Fixes variable naming problem in send_user_contact_email function

Fixes misaligned variable names in send_user_contact_email

---

expo/gbe/templates/gbe/incl_contact_form.tmpl
expo/gbe/templates/gbe/incl_lp_left.tmpl
expo/gbe/views.py

Gbe 476 - problems with contact form

---

expo/gbe/views.py

Testing fix

---

expo/gbe/functions.py
expo/gbe/models.py
expo/gbe/templates/gbe/bid_review.tmpl
expo/gbe/tests/test_edit_volunteer.py
expo/gbe/tests/test_manage_user_tickets.py
expo/gbe/tests/test_reports.py
expo/gbe/views.py

This commit hides bids from reviewers if they are associated with a previous conference. 
Also, a fair bit of code cleanup

Gbe 494 - Make bid review lists conference-aware

---

expo/tests/ticketing/test_edit_event.py
expo/tests/ticketing/test_edit_ticket.py
expo/tests/ticketing/test_list_tickets.py

@bethlakshmi should be an easy review

Three bad imports.

---

Vagrantfile

Fixes test gbe user creation

---

expo/expo/gbe_logging.py
expo/expo/settings.py
expo/gbe/views.py
expo/logs/main.log

Untangled git state, fixed some minor things.

Gbe 521: Fixed logging to allow commit

---

Vagrantfile
aliases
config/requirements.txt

Some nice extras. The way I've handled the aliases (copy them over to the vagrant user's home directory and add a line to the .bashrc to get them loaded) seems a bit crude, but it works. 
See ticket #535 for some details about what this stuff is about.

GBE-535: Adding coverage tool and some aliases

---

expo/gbe/models.py
expo/gbe/templates/gbe/bid_review_list.tmpl
expo/gbe/views.py
expo/scheduler/templates/scheduler/select_event_type.tmpl
expo/tests/factories/gbe_factories.py

Added dropdown. Note that this still links to active review pages for old bids, that will be fixed in GBE-504

Gbe 503: add conference drop-down to bid review page

---

expo/gbe/models.py
expo/gbe/views.py

Review GBE-503 first, please. Thanks.

Gbe 504: prevent review of non-current bid

---

expo/gbe/functions.py
expo/gbe/models.py
expo/scheduler/models.py
expo/scheduler/views.py
expo/tests/factories/gbe_factories.py
expo/tests/scheduler/test_add_event.py
expo/tests/scheduler/test_edit_event.py
expo/tests/scheduler/test_view_list.py

While I was at it, I cleaned up some ugly dependencies in scheduler/views.py and unified the permission functions (which were previously defined in two places)

Gbe 556: Fix filter for all events

---

expo/gbe/views.py
expo/tests/factories/gbe_factories.py
expo/tests/gbe/test_review_act.py

Gbe 554: Act coordinator act acceptance displays old conference's shows

---

expo/gbe/templates/gbe/bid_review_list.tmpl
expo/templates/base.tmpl

Added datatables and made use of them for sorting, and nicer display in
general.
Closes #387

GBE-387: Made bid tables more pretty

---

expo/gbe_forms_text.py

Gbe 332 - add "Photography/Media" to volunteer interests

---

expo/gbe/templates/gbe/fashionfair.tmpl

GBE-140: truncate long descriptions to 250 characters on display

---

expo/gbe/ticketing_idd_interface.py

Closes #601 + pep8 fixes to the file.
Reran tests, but did not make new

GBE 601:Vendor bidders get redirected to GBE 9 vendor spaces

---

expo/tests/gbe/test_edit_costume.py

Remove extraneous print statement

---

expo/scheduler/views.py

We are likely to need more here, but this was a start, and I could test it with a reasonable collection of live data.

UTF-8 encoding for teachers

---

expo/templates/base.tmpl

Sorry about the busy commit - I've set Emacs to auto-strip whitespace. Line 43 is the important one.

GBE-624: Remove hijack-release tag from base template

---

expo/gbe/forms.py
expo/gbe/functions.py
expo/gbe/models.py
expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/assign_volunteer.tmpl
expo/gbe/templates/gbe/bid_review_list.tmpl
expo/gbe/urls.py
expo/gbe/views.py
expo/gbe_forms_text.py
expo/scheduler/functions.py
expo/scheduler/models.py
expo/tests/factories/gbe_factories.py
expo/tests/gbe/test_assign_volunteer.py
expo/tests/gbe/test_edit_combo.py
expo/tests/gbe/test_get_events_and_windows.py
expo/tests/gbe/test_review_volunteer.py
expo/tests/gbe/test_review_volunteer_list.py
expo/tests/scheduler/test_get_events_and_windows.py

Fairly big change - instead of the typical accept bid flow, a new thread is introduced.  To black box test:
- go to http://localhost:8282/volunteer/reviewlist
- use a Volunteer Coordinator
- click the “Assign” link
- get the new form
——————
General layout was worked out (literally) on the back of a napkin w. @burlexpo 
The flow has not changed at all - submission goes through existing code.
Includes some bug fixes - get_sched was commented out, changes to volunteer windows affected the accuracy of the availability listings.  I added some tests to cover the regressions and hopefully prevent in future.
I left the change state code in the review screen, but removed the horrible list of events.  This allows the volunteer coordinator to reject, wait list, etc. the volunteers.

GBE 650: Better Volunteer assignment

---

expo/gbe/templates/gbe/assign_volunteer.tmpl
expo/gbe/templates/gbe/bid_review_list.tmpl
expo/gbe/templates/gbe/report/act_tech_review.tmpl
expo/templates/base.tmpl
expo/tests/gbe/test_propose_class.py
expo/tests/gbe/test_publish_proposal.py
expo/tests/gbe/test_register.py
expo/tests/gbe/test_reports.py
expo/tests/gbe/test_review_class.py
expo/tests/gbe/test_review_proposal_list.py
expo/tests/gbe/test_review_vendor.py
expo/tests/gbe/test_update_profile.py
expo/tests/gbe/test_view_act.py
expo/tests/gbe/test_view_class.py
expo/tests/gbe/test_view_troupe.py
expo/tests/gbe/test_view_vendor.py
expo/tests/gbe/test_view_volunteer.py

- has a unit test
- go to 
http://localhost:8282/reports/acttechinfo/view_summary/363
Closes #627 
To see the outcome.
- also refactored default values from the bid table and the volunteer assignment table, so we can build consistent settings across tables.

GBE 627:  Act Tech Info is now a sortable, searchable table

---

expo/gbe/__init__.py
expo/gbe/management/commands/sync_audio_downloads.py
expo/gbe/models.py
expo/gbe/receivers.py
expo/gbe/report_urls.py
expo/gbe/report_views.py
expo/gbe/templates/gbe/report/act_tech_review.tmpl

Looking into the possibilities of testing, I ran into a number of hurdles that I think we should address, but not now. 
Specifically, these center on the use of file objects in tests (ie, providing an audio track to a test object) and testing actions which alter the state of the file system (ie, testing that an action moves an object in the file system)
Since these are required for basically everything we're doing here, I haven't written any new tests for this issue. Creating new tickets to address this post-event.

Gbe 308: Bulk download of audio tracks per show

---

expo/gbe/report_views.py
expo/tests/gbe/test_reports.py

Closes #691
Includes introduction of a test to catch this.

Fix for 500 on staff area

---

expo/gbe/models.py

When we close the overall “what do we do with unicode in cdv?” problem,
I will gladly help create a unicode proof csv test framework.
Now is not that time.
Closes #681
Tested on fresh live data with all current shows.

GBE-681: 500 error on Act Tech Info

---

expo/gbe/views.py

Fix for the 500 error on costume/create

GBE-695: Fix for costume/create 500 error (redirect to persona create)

---

expo/gbe/admin.py

Small change to Admin to get a view into who is in a troupe w/out a huge multi-select list.

GBE-701: Quick ass troupe view

---

expo/gbe/templates/gbe/bio_list.tmpl
expo/gbe/views.py
expo/tests/gbe/test_bios_teachers.py

Based off other tests in the system.
closes #703

GBE 703: conference filter on teacher bios

---

expo/gbe/models.py
expo/gbe/report_views.py
expo/scheduler/models.py
expo/scheduler/views.py
expo/tests/gbe/test_review_volunteer_list.py
expo/tests/scheduler/test_contact_by_role.py

This code is horribly tangled, with different logic for each case. I've done functional testing, but it's possible I've missed something.

Gbe 672: Filter contact lists by conference

---

expo/gbe/functions.py
expo/gbe_forms_text.py
expo/scheduler/views.py
expo/tests/gbe/test_bios_teachers.py
expo/tests/scheduler/test_view_list.py
expo/tests/ticketing/test_is_excluded.py
expo/ticketing/brown_paper.py

Also, a pep8 run on brown_paper.py and eliminated print statements from tests.

Gbe 715: Eliminate case-sensitive urls in scheduler

---

expo/scheduler/views.py
expo/tests/scheduler/test_detail_view.py

GBE-717: raise 404 if someon asks for an eventitem_id that doesn't match

---

expo/gbe/models.py
expo/gbe/report_views.py
expo/gbe/ticketing_idd_interface.py
expo/scheduler/admin.py
expo/scheduler/models.py
expo/tests/functions/gbe_functions.py
expo/tests/functions/scheduler_functions.py
expo/tests/gbe/test_bios_teachers.py
expo/tests/gbe/test_get_checklist_items.py
expo/tests/gbe/test_get_checklist_items_for_roles.py
expo/tests/gbe/test_get_checklist_items_for_tickets.py
expo/tests/gbe/test_get_roles.py
expo/tests/gbe/test_has_role_in_event.py
expo/tests/gbe/test_personal_schedule.py
expo/tests/gbe/test_reports.py
expo/tests/scheduler/test_get_roles_from_scheduler.py
expo/tests/ticketing/test_edit_event.py
expo/tests/ticketing/test_edit_ticket.py
expo/tests/ticketing/test_is_excluded.py

Much more coverage.
Found 2 bugs and fixed them.
Added some reusable scheduler functions.
Closes #711

GBE-711: testing for checklist conditions

---

expo/gbe/duration.py
expo/tests/gbe/test_date_time_range.py
expo/tests/gbe/test_duration.py

Got to 91%. The missing lines are all exceptions which are not showing up as covered, even though the tests should be hitting them. In any case, I'm okay with leaving them be, though I'd like to circle back around and figure out why the coverage tool says they're not covered.

GBE-724: 91% coverage on duration.py

---

expo/gbe/views/bid_act_view.py
expo/tests/gbe/test_bid_act.py

Fix and test for missing import in bid_act_view

GBE-748: Added some missing imports

---

expo/gbe/views/edit_costume_view.py
expo/tests/gbe/test_edit_costume.py

GBE-752: fix and coverage for missing import. (100% coverage of

---

expo/gbe/views/bid_class_view.py
expo/tests/gbe/test_bid_class.py

GBE-749: Fix and test for extraneous personae in "teacher" select on

---

expo/gbe/models.py
expo/tests/factories/gbe_factories.py
expo/tests/gbe/test_clone_bid.py

@bethlakshmi I'm getting a weird failure with the ClassFactory, which is preventing the test from working - the bid object doesn't show up in the db. 
We should talk about whether this should be merged to kill the bug, or if we should hold off and try to work out what the test failure is and what it means. PR issued so you can review and consider.

Gbe 764: Fix but NO TEST for clone_bid failure

---

expo/scheduler/views.py
expo/tests/scheduler/test_view_list.py

Definitely something goofy with that ClassFactory, but it's a test.

GBE-776: Got rid of a redundant line, tested the other

---

expo/scheduler/views.py
expo/tests/contexts/__init__.py
expo/tests/contexts/class_context.py
expo/tests/contexts/staff_area_context.py
expo/tests/scheduler/test_get_roles_from_scheduler.py
expo/tests/scheduler/test_manage_volunteer_opportunities.py

Closes #778 
100% coverage on function being tested
Also fixed the cross-conference bug
And found issues with the time zones that came up as warnings during testing, so I cleaned those up.

GBE 778: Tests for manage_volunteer_opportunities

---

expo/scheduler/forms.py
expo/scheduler/views.py
expo/tests/contexts/__init__.py
expo/tests/contexts/class_context.py
expo/tests/contexts/panel_context.py
expo/tests/contexts/staff_area_context.py
expo/tests/factories/gbe_factories.py
expo/tests/functions/gbe_functions.py
expo/tests/scheduler/test_add_event.py
expo/tests/scheduler/test_view_list.py

closes #785 
- 100% coverage of add_event
- fixed the testability problem in the EventScheduler Form
- found a bug in add_event (no staff lead allocation)
- created a new context - PanelContext
- put some more reality into Class and GenericEvent Contexts to better simulate the normal case for these data sets.
- pep8 here and there

GBE-785: 100% coverage for add_event

---

expo/tests/gbe/test_review_vendor_list.py

test case asserts that all vendors created with the VendorFactory appear on the response content and also that we received a 200 status.

GBE 801: Add test case for review_vendors_list_view

---

expo/scheduler/table.py

This reverts commit 50ed0aa8d4aa6d5851910ef9059485a618837f54 which deleted the file scheduler/table.py

Revert "No reason for this?"

---

expo/gbe/views/create_vendor_view.py
expo/tests/factories/ticketing_factories.py
expo/tests/gbe/test_create_vendor.py

GBE-812: Completed coverage and updated ticketing factory

---

expo/gbe/views/edit_act_techinfo_view.py

@jonkiparsky - I got another one of the comments on 805 done.
It just abstracts a function for some of the blob of code in edit_act_techinfo, and I figured the world could use it. :)

Pull request comment update

---

expo/gbe_forms_text.py

Quick change made in the gbe_forms_text.py file.

GBE-821: Changed shifts text to the amount of hours work.

---

expo/gbe/forms.py
expo/gbe_forms_text.py

GBE-333 Legal first and last name

---

expo/gbe/expoformfields.py
expo/gbe/expomodelfields.py
expo/gbe/forms.py
expo/tests/functions/scheduler_functions.py
expo/tests/gbe/test_bid_act.py
expo/tests/gbe/test_edit_act.py
expo/tests/scheduler/test_add_event.py
expo/tests/scheduler/test_edit_event.py

closes #847
Harder than I thought, because the update was to the duration field.  Required was never really enforced.

GBE-847: make act duration required

---

expo/gbe/models/remains.py
expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/bio_list.tmpl
expo/gbe/templates/gbe/profile/incl_performer.tmpl
expo/scheduler/templates/scheduler/event_detail.tmpl
expo/tests/gbe/test_landing_page.py

- refactored “promo_small” to be promo_mini and promo_thumb for the two different sizes
- added the code to make the picture appear when it’s there, and yet justify
nicely when it’s not.
- added a test to landing_page tests

GBE-305: Now showing persona pics

---

config/requirements.txt

Do the usual fandango:
syncdb or load an existing db image, run migrations, run tests with --create-db flag first time

GBE-872: Update requirements.txt

---

expo/.coveragerc

GBE-894: Add djangobb to coverage exclusions

---

expo/scheduler/views/__init__.py
expo/scheduler/views/add_event.py
expo/scheduler/views/functions.py
expo/scheduler/views/remains.py

@BenignCremator and @gawaineo 
please try this on your machines that have a problem with GBE-679 and let’s see if it passes.
This is a small fragment of the GBE-679 cleanup work.  I figured we might be able to pull piece by piece and see where there’s a problem.
I think this is unlikely to be part of the problem, because it’s no where near Volunteer.

GBE-679 cleanup #1: just scheduler views

---

expo/scheduler/views/functions.py

I had to manually merge the scheduler area to get GBE-679 to work.  I missed a line.
This is the fix.
URGENT- because it breaks live right now due to a recent upgrade I did for Scratch to fix a different bug.

GBE-924:  Fix for GBE-679 cleanup #1 -- URGENT

---

expo/scheduler/functions.py

This pull request does about 1/2 of what the original GBE-679 cleanup pull request did.
Changes:
- scheduler/functions
- gbe/models/remains:
- pulls out Conference, ConferenceDay, VolunteerWindow, Profile, Persona, Troupe, Combo, Perfomer
My hope is to see if this avoids the problem with Volunteer seen on problem machines.
@BenignCremator or @gawaineo  - please run on your problem machines and see if this causes problems.

GBE-679 cleanup #2: some more of the tricky cleanup

---

expo/gbe/models/__init__.py
expo/gbe/models/act.py
expo/gbe/models/class_proposal.py
expo/gbe/models/costume.py
expo/gbe/models/vendor.py

I moved the simplest stuff I could find out of remains.py - this is the stuff that is Biddable, but only lightly connected elsewhere.

GBE 679 cleanup #5: inch by inch

---

config/requirements.txt
expo/expo/settings.py
expo/gbe/admin.py
expo/scheduler/admin.py
expo/tests/factories/gbe_factories.py
expo/tests/gbe/test_admin_changelist.py
expo/tests/scheduler/test_admin_changelist.py
expo/tests/ticketing/test_admin_changelist.py

This came from needing to do a big weird export, but I found a lot of places where we could update admin for easier data manipulation/visibility.
But more tuning, meant more untested code, so I wrote Admin unit tests to make sure we don’t break anything with refactoring.

GBE 947:  Better Admin

---

expo/gbe/models/profile.py
expo/gbe/templates/gbe/profile_review.tmpl
expo/gbe/views/review_profiles_view.py
expo/tests/gbe/test_review_profiles_view.py

Merged 3 fields into contact info.
Made the sortable JS-powered table.
Pulled display info out of the model
Made missing unit tests.
The pepdiff errors on profiles.py come from the stuff that’s always been there.

GBE-970: sortable, consolidated /profile/manage

---

expo/gbe/models/tech_info.py
expo/gbe/report_views.py
expo/scheduler/models.py

Found some new issues from this year’s data - cleaned them up.
This fix will need massaging when we deal with #683 - chances are, we need to do a manual merge on one or the other. 
Also urgent - this blocks stuff we need at expo run time.

GBE-990:  Fix unicode display problems

---

expo/gbe/forms/remains.py
expo/tests/gbe/test_register.py

This is:
-1 line code change (check required fields in validation)
- 2 tests - one for the bug, one for more code coverage.

GBE 1006: check for validity before using email

---

expo/gbe/forms/class_schedule_form.py
expo/tests/gbe/test_create_event.py

#1016
http://localhost:8282/create_event/Class
now shows only active users for the Teachers pull down.

GBE-2016: fix hopefully last deactivated user filter

---

expo/gbe/forms/act_edit_form.py
expo/gbe/forms/summer_act_form.py
expo/gbe/migrations/0007_conference_act_style.py
expo/gbe/migrations/0008_remove_act_is_summer.py
expo/gbe/models/act.py
expo/gbe/models/conference.py
expo/gbe/views/make_act_view.py
expo/gbe/views/review_act_view.py
expo/gbe/views/view_act_view.py
expo/gbetext.py
expo/tests/gbe/test_make_summer_act.py
expo/tests/gbe/test_review_act.py
expo/tests/gbe/test_view_summer_act.py

changed act view, edit, review, create - so it all directs you to the right act display.
To test/update:
- migrate needed.
- mark a conference as act_style = summer in the /admin.
#1062

GBE 1062: make summer/not summer an attribute of the conference.

---

expo/gbe/models/performer.py
expo/tests/gbe/test_landing_page.py

GBE-1052-fix

---

expo/gbe/static/styles/gray_grids_css/main.css
expo/tests/ticketing/test_index.py
expo/ticketing/admin.py
expo/ticketing/templates/ticketing/purchase_tickets.tmpl

None of these are bugs, just aesthetics:
- now multi-cont ready
- better admin editing and notes for how to use
- updated aesthetics per @burlexpo’s comments.

GBE 1068: tweaks to original PR

---

expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/bid.tmpl
expo/gbe/templates/gbe/bid_review.tmpl
expo/gbe/views/make_bid_view.py
expo/tests/gbe/test_create_act.py
expo/tests/gbe/test_create_class.py
expo/tests/gbe/test_create_costume.py
expo/tests/gbe/test_create_vendor.py
expo/tests/gbe/test_create_volunteer.py
expo/tests/gbe/test_make_bid.py

fix layout problems with bootstrap grid, like most other places.
I screwed up and also fixed #1079 as well as #1065 on one branch.

GBE-1065: bootstrapify bid review

---

expo/gbe/models/profile.py
expo/gbe/templates/gbe/profile/incl_shows.tmpl
expo/tests/gbe/test_landing_page.py

Now it shows the acts the person is cast for WITH the shows.

GBE 1063: avoid show repeats on included in shows

---

expo/gbe/templates/gbe/bid.tmpl
expo/gbe/views/make_class_view.py
expo/gbe/views/make_costume_view.py
expo/templates/form_table.tmpl
expo/templates/form_table_wrapper.tmpl
expo/tests/gbe/test_edit_costume.py

The problem was a misuse of inheritance.  This almost certainly came from refactoring.
Fixed it, found two bug, so created 2 tests.
Also noticed a glitch in usability of classes and fixed it.
Unit tests pass.
Testing pepdiff now.

GBE 1069: fix bugs in class & costume

---

expo/gbe/templates/gbe/act_bid_review_list.tmpl
expo/gbe/templates/gbe/bid_review_list.tmpl
expo/gbe/templates/gbe/profile_review.tmpl
expo/gbe/templates/gbe/report/act_tech_review.tmpl
expo/scheduler/templates/scheduler/event_schedule.tmpl
expo/templates/base.tmpl

If it speeds things up even a bit, I win.
And it DEFINITELY helps when I’m working offline.

GBE-1092:  Remove Datatables CSS from any page that doesn't need it

---

expo/gbe/email/views/mail_to_bidders_view.py
expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/email/mail_to_bidders.tmpl
expo/tests/gbe/email/test_mail_to_bidders.py

GBE 1137:  Email everyone button for admin

---

expo/gbe/admin.py

GBE-1150 - Fix error - b_title not e_title

---

expo/gbe/templates/gbe/act_bid_review_list.tmpl
expo/gbe/views/review_act_list_view.py
expo/tests/gbe/test_review_act_list.py

#1153 
This is an average of each ranking.
If there are no ratings, it will show as “—“ just like the ratings.
coverage running now, pepdiff and test are built.

GBE 1153:  Add average to review list

---

expo/gbe/scheduling/views/copy_occurrence_view.py
expo/tests/contexts/class_context.py
expo/tests/contexts/volunteer_context.py
expo/tests/gbe/scheduling/test_copy_occurrence_view.py

The bug was embarrassing - instead of copying the child event, I copied the parent.  Over and over again.  
The title changed but any other key details about the child were lost.
But fix, test made

GBE 1169:  Fix bug in copy

---

expo/ticketing/brown_paper.py

Revert "GBE-1159: BPT timeout - test on staging"

---

expo/gbe/templates/gbe/scheduling/event_detail.tmpl

- use thumbnails
- use the right variable reference on scheduled classes.

GBE-1181:  Find image, and thumbnail them.

---

expo/gbe/scheduling/views/functions.py
expo/gbe/scheduling/views/set_favorite_view.py
expo/gbe/templates/gbe/scheduling/event_detail.tmpl
expo/gbe/views/landing_page_view.py
expo/scheduler/idd/get_bookings.py
expo/scheduler/models.py
expo/tests/gbe/scheduling/test_detail_view.py

Fixes the case for an unscheduled class not showing presenter.
Also removes the use of deprecated function calls for roles and bios and replaces with the new get_bookings.

Release patch

---

expo/gbe/scheduling/views/make_occurrence_view.py
expo/tests/gbe/scheduling/test_edit_event_schedule.py

Do a better job of checking, instead of a query that blows up.
Write a test that could have caught this.
pepdiff good.

GBE-1193: Fix and test

---

expo/gbe/scheduling/views/make_occurrence_view.py
expo/tests/contexts/volunteer_context.py
expo/tests/gbe/scheduling/test_copy_occurrence_view.py
expo/tests/gbe/scheduling/test_detail_view.py
expo/tests/gbe/scheduling/test_edit_event_schedule.py
expo/tests/gbe/test_reports.py

Fixed the line of code and then a lot of tests.

GBE 1195:  Load Sunday Showcase for editing

---

expo/gbe/templates/gbe/report/act_tech_review.tmpl
expo/tests/gbe/reports/test_act_tech_info.py
expo/tests/gbe/test_reports.py

Fix the template, improve the test

GBE-1199: Fix act title display

---

expo/gbe/static/styles/base.css
expo/gbe/templates/gbe/report/eval_detail.tmpl

Had 2 ugly layout problems that I fixed.
And fixed the JS bug that was connected to problem from #1241

GBE-1241:  Fix JS and layout problems

---

expo/gbe/templates/gbe/report/eval_detail.tmpl

#1241 introduced a fix for this, but the fix actually obliterated some menu fuctionality.
This seems to fix it.

GBE-1252: fix the fix
